### PR TITLE
As 79 create app js

### PR DESCRIPTION
**Pull request by extrahp**

### CODE REVIEW

**Comment by TomPed** [comment]
Looks pretty good, I would say just try to get travis to pass. If you run `npm run eslint` locally you can see what you need to change (mostly spacing (instead of tabs we are using 2 spaces)).

@tkindy after travis passes can you take a look at the conflict in `app.js`

**Comment by tkindy** [comment]
@extrahp have you fixed the issues that ESLint is complaining about? If you have, push it so that Travis passes. Once those issues are fixed, I can handle the merge conflicts with the dummy server I put in app.js.

**Comment by tkindy** [comment]
There were some extra semicolons in the routing statements. I removed those, so now there's just styling issues. @extrahp, can you pull my changes and fix them?

**Comment by extrahp** [comment]
@tkindy all good to go

**Comment by TomPed** [comment]
Can we delete this branch?

**Pull request merged**
